config/routes.rb
Rails.application.routes.draw do
  root to: 'home#index'
  resources :prendas
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/guardarropa.rb
class Guardarropa < ApplicationRecord
end

app/models/prenda.rb
class Prenda < ApplicationRecord
  enum tipo: [:pantalon, :remera,:musculosa, :pollera, :zapatillas, :camisa,:'anteojos de sol',:sandalias, :short, :sombrero]
  enum categoria: [:mujer, :hombre,:unisex,:infantil ]
  enum material: [:algodon, :lino, :poliester, :seda, :denim, :cuero]
  enum color_primario: [:rojo, :amarillo, :azul,:blanco, :negro, :beige ]
  enum color_secundario: [:naranja, :rosa, :violeta,:marron, :gris]
  has_one_attached :imagen

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/guardarropas_controller.rb
class GuardarropasController < ApplicationController

    def index
        @guardarropas= Guardarropa.all
        end
      
        #get /guardarropas/:id, muestra elemento particular
        def show
    
        end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/prendas_controller.rb
# Importante:
#
# En la arquitectura MVC
# los controladores son responsables de "hablar"
# con el modelo para hacer búsquedas, actualizaciones, etc e incluso algunas operaciones que no caen en la semántica de un CRUD.
# Además, van interactuar con la información proveniente del request HTTP (por ejemplo los parámetros) e indicar qué se tiene que mostrar a continuación
#
# Por otro lado, las vistas se encargan únicamente de mostrar (dibujar aka renderizar) información. NO realizan operaciones como .all, .find, etc.
#
class PrendasController < ApplicationController

  before_action :set_prenda, only: [:show, :update, :edit, :destroy]

  # get /prendas/
  def index
    @prendas = Prenda.all
  end

  # 1. Cuando accedemos a /prendas/1, rails sabe
  # gracias a al routes.rb que hay que dirigir
  # a prendas#show, es decir, ejecutar el método
  # show de la clase (una instancia de la clase)
  # PrendasController
  #
  # 2. Luego el show en clase PrendasController accede a
  # los parámetros (mediante params) y busca en la
  # base de datos la prenda por id (find)
  #
  # 3. Implícitamente, al terminar de evaluar el método show, como no decimos nada en contrario,
  # se va a renderizar la vista views/prendas/show.hml.erb
  #
  # 4. la vista correspondiente dibuja un html utilizando
  # la variable @prenda que fue seteada previamente en el controlador

  # get /prendas/:id
  def show
  end

  # recordatorio: esto es IGUAL a lo anterior, con la salvedad
  # de que el recurso (ruta http) ahora es /prendas y rails lo mapea automáticamente
  # al método create

  # post /prendas
  def create
    Prenda.create! prenda_params # nota: prenda_params NO viene con el controller,
                                 # lo tenés que definir vos




    redirect_to action: :index
  end

  # get /prendas/new
  def new
    @prenda = Prenda.new
  end

  # put /prendas/:id
  def update
    @prenda.update! prenda_params
    redirect_to @prenda
  end

  # get /prendas/edit
  def edit
  end



  def destroy
    @prenda.destroy!
    redirect_to action: :index

  end

  private

  def set_prenda
    @prenda = Prenda.find(params[:id])

  end

  def prenda_params
    # esto vamos a hacerlo siempre así, como una receta,
    # que nos provee rails para manejar de forma segura los campos de un
    # formulario. El require va a llevar el nombre de la clase que queremos manipular
    # y el permit, los campos particulares que nos interesa admitir para editar/crear.
    params.require(:prenda).permit(:tipo,:categoria,:material,:color_primario,:color_secundario,:descripcion, :imagen)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/guardarropas_helper.rb
module GuardarropasHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/prendas_helper.rb
module PrendasHelper
end

app/views/guardarropas/index.html.erb
<h2> Tus Guardarropas</h2>

<ul>
  <%= link_to @guardarropas.first.nombre, @guardarropas.first %>
  
</ul>

app/views/home/index.html.erb
<h1>Te damos la bienvenida a QueMePongo</h1>

...resto de nuestra preciosa landing...

<%= link_to 'Mirá acá tus prendas', :prendas %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>QueMePongo</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>

    <footer>
      Copyright <%= DateTime.now.year %>
    </footer>
  </body>
</html>

app/views/prendas/edit.html.erb
<%= form_for @prenda do |f| %>
  <div id="edit">
    <div class="edit-container">
      <h2 class="title-edit">Editar producto</h2>
      <div class="form">
        <div class="form-items">
          <%= f.select :tipo, Prenda.tipos.keys, {} %>
        </div>
        <div class="form-items">
          <%= f.select :categoria, Prenda.categoria.keys, {} %>
        </div>
        <div class="form-items">
          <%= f.select :material, Prenda.materials.keys, {} %>
        </div>
        <div class="form-items">
          <%= f.select :color_primario, Prenda.color_primarios.keys, {} %>
        </div>
         <div class="form-items">
          <%= f.select :color_secundario, Prenda.color_secundarios.keys, {} %>
        </div>
        
          <%= f.text_area :descripcion %>     
        <div>
          <button class='btn-edit'><%=f.submit%></button>
        </div>
          <button class='btn-edit'><%=link_to "Volver atrás", prendas_path(@prenda) %></button>
      </div>
    </div>
  </div>
  <% if @prenda.imagen.attached? %>
    <h4>Imagen:</h4>
    <%= image_tag(@prenda.imagen) %>
  <%end %>
<% end %>

app/views/prendas/index.htm.erb
def index
    @prendas=Prenda.all
    end
  
    #get /prendas/:id, muestra elemento particular
    def show

    end

app/views/prendas/index.html.erb
<h2>Tus prendas</h2>

<ul>
  <% @prendas.each do |prenda| %>
      <li><%= link_to prenda.tipo, prenda %></li>
  <% end %>
</ul>

<%= link_to "Crear nueva prenda", new_prenda_path %>

app/views/prendas/new.html.erb
<!--

  Los formularios, ya sea que los usamos para crear (insertar en la base)
  o para modificar un objeto (modificar en la base), van a tener que estar siempre
  asociados a un objeto existente (no necesiamente sacado de la base)

  Recordar que:
    Prenda.create (instancia e inserta en la base) no es lo mismo que
    Prenda.new (solamente instancia, no inserta)

-->

<%= form_for @prenda do |f| %> <!-- esto que está acá se llama FormBuilder (rails) -->

  <%= f.select :tipo, Prenda.tipos.keys, {} %>
  <%= f.select :categoria, Prenda.categoria.keys, {} %>
  <%= f.select :material, Prenda.materials.keys, {} %>
  <%= f.select :color_primario, Prenda.color_primarios.keys, {} %>
  <%= f.select :color_secundario, Prenda.color_secundarios.keys, {} %>
  <%= f.text_area :descripcion %>
  <%= f.label :imagen %>
  <%= f.file_field :imagen %>


  <%= f.submit %>
<% end %>

<%= link_to "Volver atrás", prendas_path(@prenda) %>

app/views/prendas/show.html.erb
<div id="show">
  <div class="show-container">
    <h2>Informacion sobre la prenda</h2>
    <figure class="about-section-image">
     <% if @prenda.imagen.attached? %>
        <h3>Imagen:</h3>
        <%= image_tag(@prenda.imagen) %>
      <% else %>
        <h3>Imagen:</h3>
        <img src="/assets/no_hay_imagen.jpg" alt="no_hay_imagen">
     <%end %>
    </figure>
    <section class="text-about">
      <h3>Tipo:<%= @prenda.tipo %></h3>
      <h3>Categoria:<%= @prenda.categoria %></h3>
      <h3>Material:<%= @prenda.material %></h3>
      <h3>Color Primario:<%= @prenda.color_primario %></h3>
      <h3>Color Secundario:<%= @prenda.color_secundario %></h3>
      <h3>Descripcion:<%= @prenda.descripcion %></h3>
    </section>
    <button class='button-dis'>
    sadas
    </button>
    <%= link_to "Editar esta prenda", edit_prenda_path(@prenda) %>
    <%= link_to "Borrar esta prenda", @prenda, method: "delete", data: {confirm: 'Estas seguro?'} %>
    <%= link_to "Volver atrás", prendas_path(@prenda) %>
   

  </div>
</div>